import { PlayerId } from '../../shared';
export declare class GameView extends HTMLElement {
    private static readonly WINNER_SCORE;
    private static readonly START_SCORE;
    private static readonly VELOCITY_TO_SCORE_FACTOR;
    private static readonly MAX_SCORE;
    private static readonly THROTTLE_LIMIT;
    private static velocityToScore;
    private readonly gesture;
    private gameStarted;
    private playerOneScore;
    private playerTwoScore;
    private $playerOneContainer;
    private $playerTwoContainer;
    private $playerOneScore;
    private $playerTwoScore;
    private $playerOneWins;
    private $playerTwoWins;
    wins: Record<PlayerId, number>;
    private readonly win;
    readonly playerOneIsWinner: boolean;
    readonly playerTwoIsWinner: boolean;
    connectedCallback(): void;
    disconnectedCallback(): void;
    private onWinsChanges;
    private onStartCountdownDone;
    private onPanMove;
    private updateScores;
    private checkWinner;
    private resetGame;
    private normalizeScore;
    private render;
    private animatePlayerContainer;
    private animateView;
}
